### ISSUE TITLE
Exercises for NodeJS and Ruby on Rails

### ISSUE THREAD

**Issue by aaron-suarez** [sk4ddy/remediatetheflag#11]
Quick question:

In `docs/create.md`, it states:

The following technology stacks are available for download:

* [Java / Apache Tomcat / MySQL / Eclipse](https://bitbucket.org/remediatetheflag/rtf-docker-templates/src/3fdf01d7d4b2aec5bc4fe97cf464315417abf356?at=master)
* NodeJS / Redis / Mongo / Atom
* Ruby on Rails / MySQL / Atom 

Ruby on Rails and NodeJS do not have docker images linked. Are they still a work in progress, and if so, where would someone get involved with development of these exercises? 

If they are finished, where is the download link for these exercises? I'm happy to do a PR to the docs to add the download link.

Thanks!

(P.S., the Java exercises were pretty fun, great work on that)

**Comment by remediatetheflag** [comment]
We won't be publishing images for other technologies for RTF 1.0. The new RTF release will feature a cli SDK for rapid exercise creation/publishing starting from base images in Java, NodeJS, Ruby, Python, .NET, Go, Solidity (more will be added later). You will also be able to install new exercises on your RTF deployment from the RTF Exercise Hub tab in the management interface.

**Comment by aaron-suarez** [comment]
Ok, thanks for the info. Do you have any timeline for when this new version of RTF will be available? Or any information on how to contribute to developing it?

**Comment by remediatetheflag** [comment]
We should be releasing at the end of July / early August. We're investing in creating documentation so that it will be easier to contribute!
