### ISSUE TITLE
GetStatsGlobalAction class throw error for specific organization when filtering

### ISSUE THREAD

**Issue by VictorioDev** [sk4ddy/remediatetheflag#14]
Hello!

We are having a problem in the stats dashboard while browsing as manager. I'm trying to figure out why its hapenning, but the fact is that when i check an especific Organization (Sadly, that one who has more users interacting with the platform) in filter, i get error response from the server and the page can't display the statistics. When i uncheck this organization, it comes back to work properly.
I tried with diferente manager users and also to put these users in the same organization, but nothing solve the issue.
The platform where working in the beginning but after adding a few more users this issue appeared.
Looking at the log files in the server i saw that it throws an error while trying to process the request and logs this message:

![log](https://user-images.githubusercontent.com/13885753/64887054-1202ca80-d63e-11e9-990f-e39a49c6cb95.png)

It shows a user number, more precisely the one who is logged in the platform at that moment follewed by a "null", that acording to the code in GetStatsGlobalAction.java is the error message.
It's hard to discover the problem that is occurring, once that the message content is null.

Can you give us a instruction for where to starts to look to possibly solve this problem?
I'm leaving these images below that ilustrates the problem:

![dashBoardEmptyEdit](https://user-images.githubusercontent.com/13885753/64966855-ec600600-d875-11e9-9584-f8a20a120f68.png)
![dashBoardFullEdited](https://user-images.githubusercontent.com/13885753/64966856-ecf89c80-d875-11e9-8208-f11c5a22a552.png)

You did a great work building this platform. Thank you!

**Comment by remediatetheflag** [comment]
Unfortunately error handling is not great in this version.  
Can you please modify the code in [ActionsController](https://github.com/sk4ddy/remediatetheflag/blob/master/RTF-Portal/src/main/java/com/remediatetheflag/global/controllers/ActionsController.java#L162) (line 162) to:
```
StringWriter errors = new StringWriter();
e.printStackTrace(new PrintWriter(errors));
logger.error("Action Exception: "+actionClass.toString()+" for user: "+usr+"\n" + e.getMessage()+"\n"+errors.toString() );
```
			
This logs the stacktrace and should provide a better indication of problems arising from unhandled exceptions.

**Comment by VictorioDev** [comment]
I didn't find a way to interact with the Java code in the platform because the source code is compiled and placed in tomcat folder and can't be modified in this way.
Where do i need to place the compiled Java code to be used when building the container ? What's is the worflow that you used while developing the platform to be able to modify the code and see the changes in production in a quick way without need to rebuild the services container all the time? (I don't think is possible, but we are avoiding restarting it because we don't  want to loose the data)

Thank you for reply.
