### ISSUE TITLE
Master template not public

### ISSUE THREAD

**Issue by aaron-suarez** [sk4ddy/remediatetheflag#4]
Following the [installation instructions](https://github.com/sk4ddy/remediatetheflag/blob/master/docs/install.md), there is a link to https://s3-eu-west-1.amazonaws.com/rtf-public-templates/rtf-template.yaml

This template (though it says "public-templates" in the URL) is not public. If you follow this link directly, you get an XML response similar to:

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>1D6CD33AEA5A7EBB</RequestId>
  <HostId>
    oNVqNB4s8Z9OsJuFTQHE6Ch37YpSp2BDv+rnHbVMp7gc9qiTxLTwa28wDpWQFv7ySp8xgFpBVqI=
  </HostId>
</Error>
```

If you continue to follow the instructions anyway, you see the following errors:

```
Cannot open this file because of an error.: https://s3-eu-west-1.amazonaws.com/rtf-public-templates/rtf-template.yaml must reference a valid S3 object to which you have access.
```
and
```
Template validation error: S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
```

Should these instructions be updated to reflect a new URL location? If a decision was made to keep this particular S3 object private instead of public, should the instructions be updated to import from https://github.com/sk4ddy/remediatetheflag/blob/master/RTF-CloudformationTemplates/rtf-template.yaml instead?

I'm happy to do a PR, please advise on what these instructions should say.

**Comment by remediatetheflag** [comment]
Apologies, permissions on S3 mixed up on the latest update. Even if the bucket is public, when you upload files it doesn't default to public.

**Comment by aaron-suarez** [comment]
Thanks, it's working properly now!
